version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: WordTemplateProcessor.web/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production